# Generated by Django 5.0.4 on 2024-04-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movmensalista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movmensalista',
            name='dt_pago',
            field=models.DateField(),
        ),
    ]
